"""fix_skus_table

Revision ID: 3048c78aed0b
Revises: 
Create Date: 2026-05-10 12:03:42.789644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3048c78aed0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('skus_seller_id_fkey', 'skus', type_='foreignkey')
    op.drop_column('skus', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('skus_seller_id_fkey', 'skus', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###
