"""add_ralationship_between_sku_and_characteristics

Revision ID: b2f58976dc2b
Revises: 3048c78aed0b
Create Date: 2026-05-10 14:33:19.585710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f58976dc2b'
down_revision: Union[str, Sequence[str], None] = '3048c78aed0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
